# Generated by Django 3.2.8 on 2021-10-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=256)),
                ('option_a', models.CharField(max_length=64)),
                ('option_b', models.CharField(max_length=64)),
                ('option_c', models.CharField(max_length=64)),
                ('option_d', models.CharField(max_length=64)),
                ('correct', models.CharField(max_length=1)),
                ('link', models.CharField(max_length=128)),
            ],
        ),
    ]
